package com.main.db.dao;

import com.main.db.model.WmMainMembers;
import com.main.db.model.WmMainMembersExample;
import com.main.db.model.WmMainMembersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WmMainMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_MEMBERS
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int countByExample(WmMainMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_MEMBERS
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int deleteByExample(WmMainMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_MEMBERS
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int deleteByPrimaryKey(WmMainMembersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_MEMBERS
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int insert(WmMainMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_MEMBERS
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int insertSelective(WmMainMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_MEMBERS
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    List<WmMainMembers> selectByExample(WmMainMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_MEMBERS
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    WmMainMembers selectByPrimaryKey(WmMainMembersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_MEMBERS
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int updateByExampleSelective(@Param("record") WmMainMembers record, @Param("example") WmMainMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_MEMBERS
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int updateByExample(@Param("record") WmMainMembers record, @Param("example") WmMainMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_MEMBERS
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int updateByPrimaryKeySelective(WmMainMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_MEMBERS
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int updateByPrimaryKey(WmMainMembers record);
}