package com.main.db.dao;

import com.main.db.model.WmMainAuthtoken;
import com.main.db.model.WmMainAuthtokenExample;
import com.main.db.model.WmMainAuthtokenKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WmMainAuthtokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHTOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int countByExample(WmMainAuthtokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHTOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int deleteByExample(WmMainAuthtokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHTOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int deleteByPrimaryKey(WmMainAuthtokenKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHTOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int insert(WmMainAuthtoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHTOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int insertSelective(WmMainAuthtoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHTOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    List<WmMainAuthtoken> selectByExample(WmMainAuthtokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHTOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    WmMainAuthtoken selectByPrimaryKey(WmMainAuthtokenKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHTOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") WmMainAuthtoken record, @Param("example") WmMainAuthtokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHTOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int updateByExample(@Param("record") WmMainAuthtoken record, @Param("example") WmMainAuthtokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHTOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int updateByPrimaryKeySelective(WmMainAuthtoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHTOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int updateByPrimaryKey(WmMainAuthtoken record);
}