package com.main.db.dao;

import com.main.db.model.WmMainAuthcookie;
import com.main.db.model.WmMainAuthcookieExample;
import com.main.db.model.WmMainAuthcookieKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WmMainAuthcookieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHCOOKIE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int countByExample(WmMainAuthcookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHCOOKIE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int deleteByExample(WmMainAuthcookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHCOOKIE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int deleteByPrimaryKey(WmMainAuthcookieKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHCOOKIE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int insert(WmMainAuthcookie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHCOOKIE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int insertSelective(WmMainAuthcookie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHCOOKIE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    List<WmMainAuthcookie> selectByExample(WmMainAuthcookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHCOOKIE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    WmMainAuthcookie selectByPrimaryKey(WmMainAuthcookieKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHCOOKIE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") WmMainAuthcookie record, @Param("example") WmMainAuthcookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHCOOKIE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int updateByExample(@Param("record") WmMainAuthcookie record, @Param("example") WmMainAuthcookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHCOOKIE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int updateByPrimaryKeySelective(WmMainAuthcookie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_MAIN_AUTHCOOKIE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int updateByPrimaryKey(WmMainAuthcookie record);
}