package com.main.db.dao;

import com.main.db.model.WmSysSysid;
import com.main.db.model.WmSysSysidExample;
import com.main.db.model.WmSysSysidKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WmSysSysidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    int countByExample(WmSysSysidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    int deleteByExample(WmSysSysidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    int deleteByPrimaryKey(WmSysSysidKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    int insert(WmSysSysid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    int insertSelective(WmSysSysid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    List<WmSysSysid> selectByExample(WmSysSysidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    WmSysSysid selectByPrimaryKey(WmSysSysidKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") WmSysSysid record, @Param("example") WmSysSysidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    int updateByExample(@Param("record") WmSysSysid record, @Param("example") WmSysSysidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    int updateByPrimaryKeySelective(WmSysSysid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    int updateByPrimaryKey(WmSysSysid record);
}