package com.main.db.dao;

import com.main.db.model.WmSysConfig;
import com.main.db.model.WmSysConfigExample;
import com.main.db.model.WmSysConfigKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WmSysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int countByExample(WmSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int deleteByExample(WmSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int deleteByPrimaryKey(WmSysConfigKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int insert(WmSysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int insertSelective(WmSysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    List<WmSysConfig> selectByExample(WmSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    WmSysConfig selectByPrimaryKey(WmSysConfigKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int updateByExampleSelective(@Param("record") WmSysConfig record, @Param("example") WmSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int updateByExample(@Param("record") WmSysConfig record, @Param("example") WmSysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int updateByPrimaryKeySelective(WmSysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CONFIG
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    int updateByPrimaryKey(WmSysConfig record);
}