package com.main.db.dao;

import com.main.db.model.WmSysCode;
import com.main.db.model.WmSysCodeExample;
import com.main.db.model.WmSysCodeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WmSysCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CODE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int countByExample(WmSysCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CODE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int deleteByExample(WmSysCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CODE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int deleteByPrimaryKey(WmSysCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CODE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int insert(WmSysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CODE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int insertSelective(WmSysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CODE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    List<WmSysCode> selectByExample(WmSysCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CODE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    WmSysCode selectByPrimaryKey(WmSysCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CODE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") WmSysCode record, @Param("example") WmSysCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CODE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int updateByExample(@Param("record") WmSysCode record, @Param("example") WmSysCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CODE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int updateByPrimaryKeySelective(WmSysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_CODE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    int updateByPrimaryKey(WmSysCode record);
}