package com.main.db.model;

public class WmMainAuthcode extends WmMainAuthcodeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_MAIN_AUTHCODE.IDNO
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    private String idno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_MAIN_AUTHCODE.EXPIRED_TIME
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    private String expiredTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_MAIN_AUTHCODE.SYS_ID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    private String sysId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_MAIN_AUTHCODE.IDNO
     *
     * @return the value of WM_MAIN_AUTHCODE.IDNO
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_MAIN_AUTHCODE.IDNO
     *
     * @param idno the value for WM_MAIN_AUTHCODE.IDNO
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    public void setIdno(String idno) {
        this.idno = idno == null ? null : idno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_MAIN_AUTHCODE.EXPIRED_TIME
     *
     * @return the value of WM_MAIN_AUTHCODE.EXPIRED_TIME
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    public String getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_MAIN_AUTHCODE.EXPIRED_TIME
     *
     * @param expiredTime the value for WM_MAIN_AUTHCODE.EXPIRED_TIME
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    public void setExpiredTime(String expiredTime) {
        this.expiredTime = expiredTime == null ? null : expiredTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_MAIN_AUTHCODE.SYS_ID
     *
     * @return the value of WM_MAIN_AUTHCODE.SYS_ID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_MAIN_AUTHCODE.SYS_ID
     *
     * @param sysId the value for WM_MAIN_AUTHCODE.SYS_ID
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    public void setSysId(String sysId) {
        this.sysId = sysId == null ? null : sysId.trim();
    }
}