package com.main.db.model;

public class WmMainAuthtokenKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_MAIN_AUTHTOKEN.TOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_MAIN_AUTHTOKEN.TOKEN
     *
     * @return the value of WM_MAIN_AUTHTOKEN.TOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_MAIN_AUTHTOKEN.TOKEN
     *
     * @param token the value for WM_MAIN_AUTHTOKEN.TOKEN
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}