package com.main.db.model;

public class WmMainMembers extends WmMainMembersKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_MAIN_MEMBERS.NAME
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_MAIN_MEMBERS.SEX
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_MAIN_MEMBERS.ACCOUNT_SEQ
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    private String accountSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_MAIN_MEMBERS.NAME
     *
     * @return the value of WM_MAIN_MEMBERS.NAME
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_MAIN_MEMBERS.NAME
     *
     * @param name the value for WM_MAIN_MEMBERS.NAME
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_MAIN_MEMBERS.SEX
     *
     * @return the value of WM_MAIN_MEMBERS.SEX
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_MAIN_MEMBERS.SEX
     *
     * @param sex the value for WM_MAIN_MEMBERS.SEX
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_MAIN_MEMBERS.ACCOUNT_SEQ
     *
     * @return the value of WM_MAIN_MEMBERS.ACCOUNT_SEQ
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    public String getAccountSeq() {
        return accountSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_MAIN_MEMBERS.ACCOUNT_SEQ
     *
     * @param accountSeq the value for WM_MAIN_MEMBERS.ACCOUNT_SEQ
     *
     * @mbggenerated Mon Jun 06 14:48:35 CST 2016
     */
    public void setAccountSeq(String accountSeq) {
        this.accountSeq = accountSeq == null ? null : accountSeq.trim();
    }
}