package com.main.db.model;

public class WmMainAuthcookieKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_MAIN_AUTHCOOKIE.COOKIE_ID
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    private String cookieId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_MAIN_AUTHCOOKIE.COOKIE_ID
     *
     * @return the value of WM_MAIN_AUTHCOOKIE.COOKIE_ID
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public String getCookieId() {
        return cookieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_MAIN_AUTHCOOKIE.COOKIE_ID
     *
     * @param cookieId the value for WM_MAIN_AUTHCOOKIE.COOKIE_ID
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public void setCookieId(String cookieId) {
        this.cookieId = cookieId == null ? null : cookieId.trim();
    }
}