package com.main.db.model;

public class WmMainMembersKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_MAIN_MEMBERS.IDNO
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    private String idno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_MAIN_MEMBERS.IDNO
     *
     * @return the value of WM_MAIN_MEMBERS.IDNO
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_MAIN_MEMBERS.IDNO
     *
     * @param idno the value for WM_MAIN_MEMBERS.IDNO
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public void setIdno(String idno) {
        this.idno = idno == null ? null : idno.trim();
    }
}