package com.main.db.model;

public class WmSysSysidKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_SYS_SYSID.SYS_ID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    private String sysId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_SYS_SYSID.SYS_ID
     *
     * @return the value of WM_SYS_SYSID.SYS_ID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_SYS_SYSID.SYS_ID
     *
     * @param sysId the value for WM_SYS_SYSID.SYS_ID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public void setSysId(String sysId) {
        this.sysId = sysId == null ? null : sysId.trim();
    }
}