package com.main.db.model;

public class WmSysCode extends WmSysCodeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_SYS_CODE.CODE_TEXT
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    private String codeText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_SYS_CODE.CODE_DESCRIPTION
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    private String codeDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_SYS_CODE.CODE_SEQ
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    private Integer codeSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_SYS_CODE.CODE_TEXT
     *
     * @return the value of WM_SYS_CODE.CODE_TEXT
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public String getCodeText() {
        return codeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_SYS_CODE.CODE_TEXT
     *
     * @param codeText the value for WM_SYS_CODE.CODE_TEXT
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public void setCodeText(String codeText) {
        this.codeText = codeText == null ? null : codeText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_SYS_CODE.CODE_DESCRIPTION
     *
     * @return the value of WM_SYS_CODE.CODE_DESCRIPTION
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public String getCodeDescription() {
        return codeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_SYS_CODE.CODE_DESCRIPTION
     *
     * @param codeDescription the value for WM_SYS_CODE.CODE_DESCRIPTION
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public void setCodeDescription(String codeDescription) {
        this.codeDescription = codeDescription == null ? null : codeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_SYS_CODE.CODE_SEQ
     *
     * @return the value of WM_SYS_CODE.CODE_SEQ
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public Integer getCodeSeq() {
        return codeSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_SYS_CODE.CODE_SEQ
     *
     * @param codeSeq the value for WM_SYS_CODE.CODE_SEQ
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public void setCodeSeq(Integer codeSeq) {
        this.codeSeq = codeSeq;
    }
}