package com.main.db.model;

public class WmSysConfig extends WmSysConfigKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_SYS_CONFIG.CONFIG_VALUE
     *
     * @mbggenerated Thu Apr 14 16:59:04 CST 2016
     */
    private String configValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_SYS_CONFIG.CONFIG_VALUE
     *
     * @return the value of WM_SYS_CONFIG.CONFIG_VALUE
     *
     * @mbggenerated Thu Apr 14 16:59:04 CST 2016
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_SYS_CONFIG.CONFIG_VALUE
     *
     * @param configValue the value for WM_SYS_CONFIG.CONFIG_VALUE
     *
     * @mbggenerated Thu Apr 14 16:59:04 CST 2016
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }
}