package com.main.db.model;

import java.util.ArrayList;
import java.util.List;

public class WmSysSysidExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public WmSysSysidExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysIdIsNull() {
            addCriterion("SYS_ID is null");
            return (Criteria) this;
        }

        public Criteria andSysIdIsNotNull() {
            addCriterion("SYS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSysIdEqualTo(String value) {
            addCriterion("SYS_ID =", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotEqualTo(String value) {
            addCriterion("SYS_ID <>", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdGreaterThan(String value) {
            addCriterion("SYS_ID >", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_ID >=", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdLessThan(String value) {
            addCriterion("SYS_ID <", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdLessThanOrEqualTo(String value) {
            addCriterion("SYS_ID <=", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdLike(String value) {
            addCriterion("SYS_ID like", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotLike(String value) {
            addCriterion("SYS_ID not like", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdIn(List<String> values) {
            addCriterion("SYS_ID in", values, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotIn(List<String> values) {
            addCriterion("SYS_ID not in", values, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdBetween(String value1, String value2) {
            addCriterion("SYS_ID between", value1, value2, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotBetween(String value1, String value2) {
            addCriterion("SYS_ID not between", value1, value2, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysNameIsNull() {
            addCriterion("SYS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSysNameIsNotNull() {
            addCriterion("SYS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSysNameEqualTo(String value) {
            addCriterion("SYS_NAME =", value, "sysName");
            return (Criteria) this;
        }

        public Criteria andSysNameNotEqualTo(String value) {
            addCriterion("SYS_NAME <>", value, "sysName");
            return (Criteria) this;
        }

        public Criteria andSysNameGreaterThan(String value) {
            addCriterion("SYS_NAME >", value, "sysName");
            return (Criteria) this;
        }

        public Criteria andSysNameGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_NAME >=", value, "sysName");
            return (Criteria) this;
        }

        public Criteria andSysNameLessThan(String value) {
            addCriterion("SYS_NAME <", value, "sysName");
            return (Criteria) this;
        }

        public Criteria andSysNameLessThanOrEqualTo(String value) {
            addCriterion("SYS_NAME <=", value, "sysName");
            return (Criteria) this;
        }

        public Criteria andSysNameLike(String value) {
            addCriterion("SYS_NAME like", value, "sysName");
            return (Criteria) this;
        }

        public Criteria andSysNameNotLike(String value) {
            addCriterion("SYS_NAME not like", value, "sysName");
            return (Criteria) this;
        }

        public Criteria andSysNameIn(List<String> values) {
            addCriterion("SYS_NAME in", values, "sysName");
            return (Criteria) this;
        }

        public Criteria andSysNameNotIn(List<String> values) {
            addCriterion("SYS_NAME not in", values, "sysName");
            return (Criteria) this;
        }

        public Criteria andSysNameBetween(String value1, String value2) {
            addCriterion("SYS_NAME between", value1, value2, "sysName");
            return (Criteria) this;
        }

        public Criteria andSysNameNotBetween(String value1, String value2) {
            addCriterion("SYS_NAME not between", value1, value2, "sysName");
            return (Criteria) this;
        }

        public Criteria andSysPasswordIsNull() {
            addCriterion("SYS_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andSysPasswordIsNotNull() {
            addCriterion("SYS_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andSysPasswordEqualTo(String value) {
            addCriterion("SYS_PASSWORD =", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordNotEqualTo(String value) {
            addCriterion("SYS_PASSWORD <>", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordGreaterThan(String value) {
            addCriterion("SYS_PASSWORD >", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_PASSWORD >=", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordLessThan(String value) {
            addCriterion("SYS_PASSWORD <", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordLessThanOrEqualTo(String value) {
            addCriterion("SYS_PASSWORD <=", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordLike(String value) {
            addCriterion("SYS_PASSWORD like", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordNotLike(String value) {
            addCriterion("SYS_PASSWORD not like", value, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordIn(List<String> values) {
            addCriterion("SYS_PASSWORD in", values, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordNotIn(List<String> values) {
            addCriterion("SYS_PASSWORD not in", values, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordBetween(String value1, String value2) {
            addCriterion("SYS_PASSWORD between", value1, value2, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysPasswordNotBetween(String value1, String value2) {
            addCriterion("SYS_PASSWORD not between", value1, value2, "sysPassword");
            return (Criteria) this;
        }

        public Criteria andSysIpIsNull() {
            addCriterion("SYS_IP is null");
            return (Criteria) this;
        }

        public Criteria andSysIpIsNotNull() {
            addCriterion("SYS_IP is not null");
            return (Criteria) this;
        }

        public Criteria andSysIpEqualTo(String value) {
            addCriterion("SYS_IP =", value, "sysIp");
            return (Criteria) this;
        }

        public Criteria andSysIpNotEqualTo(String value) {
            addCriterion("SYS_IP <>", value, "sysIp");
            return (Criteria) this;
        }

        public Criteria andSysIpGreaterThan(String value) {
            addCriterion("SYS_IP >", value, "sysIp");
            return (Criteria) this;
        }

        public Criteria andSysIpGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_IP >=", value, "sysIp");
            return (Criteria) this;
        }

        public Criteria andSysIpLessThan(String value) {
            addCriterion("SYS_IP <", value, "sysIp");
            return (Criteria) this;
        }

        public Criteria andSysIpLessThanOrEqualTo(String value) {
            addCriterion("SYS_IP <=", value, "sysIp");
            return (Criteria) this;
        }

        public Criteria andSysIpLike(String value) {
            addCriterion("SYS_IP like", value, "sysIp");
            return (Criteria) this;
        }

        public Criteria andSysIpNotLike(String value) {
            addCriterion("SYS_IP not like", value, "sysIp");
            return (Criteria) this;
        }

        public Criteria andSysIpIn(List<String> values) {
            addCriterion("SYS_IP in", values, "sysIp");
            return (Criteria) this;
        }

        public Criteria andSysIpNotIn(List<String> values) {
            addCriterion("SYS_IP not in", values, "sysIp");
            return (Criteria) this;
        }

        public Criteria andSysIpBetween(String value1, String value2) {
            addCriterion("SYS_IP between", value1, value2, "sysIp");
            return (Criteria) this;
        }

        public Criteria andSysIpNotBetween(String value1, String value2) {
            addCriterion("SYS_IP not between", value1, value2, "sysIp");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessIsNull() {
            addCriterion("REDIRECT_LOGIN_SUCCESS is null");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessIsNotNull() {
            addCriterion("REDIRECT_LOGIN_SUCCESS is not null");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessEqualTo(String value) {
            addCriterion("REDIRECT_LOGIN_SUCCESS =", value, "redirectLoginSuccess");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessNotEqualTo(String value) {
            addCriterion("REDIRECT_LOGIN_SUCCESS <>", value, "redirectLoginSuccess");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessGreaterThan(String value) {
            addCriterion("REDIRECT_LOGIN_SUCCESS >", value, "redirectLoginSuccess");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessGreaterThanOrEqualTo(String value) {
            addCriterion("REDIRECT_LOGIN_SUCCESS >=", value, "redirectLoginSuccess");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessLessThan(String value) {
            addCriterion("REDIRECT_LOGIN_SUCCESS <", value, "redirectLoginSuccess");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessLessThanOrEqualTo(String value) {
            addCriterion("REDIRECT_LOGIN_SUCCESS <=", value, "redirectLoginSuccess");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessLike(String value) {
            addCriterion("REDIRECT_LOGIN_SUCCESS like", value, "redirectLoginSuccess");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessNotLike(String value) {
            addCriterion("REDIRECT_LOGIN_SUCCESS not like", value, "redirectLoginSuccess");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessIn(List<String> values) {
            addCriterion("REDIRECT_LOGIN_SUCCESS in", values, "redirectLoginSuccess");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessNotIn(List<String> values) {
            addCriterion("REDIRECT_LOGIN_SUCCESS not in", values, "redirectLoginSuccess");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessBetween(String value1, String value2) {
            addCriterion("REDIRECT_LOGIN_SUCCESS between", value1, value2, "redirectLoginSuccess");
            return (Criteria) this;
        }

        public Criteria andRedirectLoginSuccessNotBetween(String value1, String value2) {
            addCriterion("REDIRECT_LOGIN_SUCCESS not between", value1, value2, "redirectLoginSuccess");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 06 15:02:45 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WM_SYS_SYSID
     *
     * @mbggenerated Mon Jun 06 15:02:45 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}