package com.main.db.model;

public class WmSysCodeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_SYS_CODE.CODE_NAME
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    private String codeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WM_SYS_CODE.CODE_VALUE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    private String codeValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_SYS_CODE.CODE_NAME
     *
     * @return the value of WM_SYS_CODE.CODE_NAME
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_SYS_CODE.CODE_NAME
     *
     * @param codeName the value for WM_SYS_CODE.CODE_NAME
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WM_SYS_CODE.CODE_VALUE
     *
     * @return the value of WM_SYS_CODE.CODE_VALUE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public String getCodeValue() {
        return codeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WM_SYS_CODE.CODE_VALUE
     *
     * @param codeValue the value for WM_SYS_CODE.CODE_VALUE
     *
     * @mbggenerated Mon Jun 06 15:53:35 CST 2016
     */
    public void setCodeValue(String codeValue) {
        this.codeValue = codeValue == null ? null : codeValue.trim();
    }
}